blank_issues_enabled: false
contact_links:
  - name: Content or feature request
    url: https://github.com/mdn/mdn/issues/new/choose
    about: Propose new content for MDN Web Docs or submit a feature request using this link.
  - name: MDN GitHub Discussions
    url: https://github.com/orgs/mdn/discussions
    about: Does your topic involve a lot of pages, or are you not sure how it can be split into actionable tasks? Consider starting a discussion first.
